use ast_grep_core::{Node, Language};
use ast_grep_language::{SupportLang, LanguageExt};
use ignore::WalkBuilder;
use serde::Serialize;
use std::fs;
use std::path::Path;
use std::env;
use chrono::Utc;

#[derive(Serialize)]
struct CodebaseJson {
    generated: String,
    generator: String,
    note: String,
    files: Vec<FileInfo>,
}

#[derive(Serialize)]
struct FileInfo {
    path: String,
    #[serde(rename = "type")]
    file_type: String,
    exports: Vec<String>,
    description: String,
}

fn determine_lang(path: &Path) -> Option<SupportLang> {
    let ext = path.extension()?.to_str()?;
    match ext {
        "js" | "jsx" => Some(SupportLang::JavaScript),
        "ts" | "tsx" => Some(SupportLang::TypeScript),
        "rs" => Some(SupportLang::Rust),
        "py" => Some(SupportLang::Python),
        "go" => Some(SupportLang::Go),
        "cpp" | "cxx" | "cc" | "h" | "hpp" => Some(SupportLang::Cpp),
        "c" => Some(SupportLang::C),
        "java" => Some(SupportLang::Java),
        "cs" => Some(SupportLang::CSharp),
        "rb" => Some(SupportLang::Ruby),
        "php" => Some(SupportLang::Php),
        "swift" => Some(SupportLang::Swift),
        "kt" | "kts" => Some(SupportLang::Kotlin),
        "html" => Some(SupportLang::Html),
        "css" => Some(SupportLang::Css),
        _ => None,
    }
}

fn extract_symbols<'a, D: ast_grep_core::Doc>(node: Node<'a, D>, symbols: &mut Vec<String>) {
    let kind = node.kind();
    
    // Generic heuristic for finding important symbols across any tree-sitter grammar
    if kind.contains("function_declaration") || kind.contains("function_item") 
        || kind.contains("class_declaration") || kind.contains("struct_item")
        || kind.contains("export_statement") 
        || kind.contains("impl_item") {
        
        // Try to find an identifier child which usually holds the name
        let name = node.children().find(|c| c.kind().contains("identifier") || c.kind() == "type_identifier");
        if let Some(n) = name {
            symbols.push(n.text().to_string());
        }
    }
    
    for child in node.children() {
        extract_symbols(child, symbols);
    }
}

fn process_file(path: &Path) -> Option<FileInfo> {
    let lang = determine_lang(path)?;
    let content = fs::read_to_string(path).ok()?;
    
    // Parse using ast-grep
    let root = lang.ast_grep(content);
    let mut symbols = Vec::new();
    
    extract_symbols(root.root(), &mut symbols);
    
    symbols.sort();
    symbols.dedup();
    
    let rel_path = path.strip_prefix(env::current_dir().unwrap_or_default())
        .unwrap_or(path)
        .display()
        .to_string()
        .replace("\\", "/");
        
    let file_type = if rel_path.starts_with("src/") { "frontend" }
                    else if rel_path.starts_with("src-tauri/") { "backend" }
                    else if rel_path.starts_with("tools/") { "tools" }
                    else { "other" };

    Some(FileInfo {
        path: rel_path,
        file_type: file_type.to_string(),
        exports: symbols,
        description: "Auto-indexed signatures".to_string(),
    })
}

fn main() {
    println!("Starting Silice AST Indexer...");
    let root_dir = env::current_dir().unwrap();
    
    let mut files_info = Vec::new();
    
    for result in WalkBuilder::new(&root_dir)
        .hidden(false)
        .git_ignore(true)
        .build() 
    {
        let entry = match result {
            Ok(e) => e,
            Err(_) => continue,
        };
        
        let path = entry.path();
        if path.is_file() {
            let p_str = path.display().to_string();
            // Skip target and node_modules explicitly if git_ignore doesn't catch them
            if p_str.contains("node_modules") || p_str.contains("target") || p_str.contains("dist") || p_str.contains(".git") {
                continue;
            }
            
            if let Some(info) = process_file(path) {
                if !info.exports.is_empty() {
                    files_info.push(info);
                }
            }
        }
    }
    
    let db = CodebaseJson {
        generated: Utc::now().to_rfc3339(),
        generator: "ast-indexer".to_string(),
        note: "Auto-generated by Rust AST Indexer via git pre-commit hook.".to_string(),
        files: files_info,
    };
    
    let json = serde_json::to_string_pretty(&db).unwrap();
    let out_path = root_dir.join("silice").join("codebase.json");
    
    // Ensure silice directory exists
    if let Some(parent) = out_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    
    fs::write(&out_path, json).expect("Failed to write codebase.json");
    println!("Successfully indexed codebase.json at {}", out_path.display());
}
